"use strict";

/** @type {import('sequelize-cli').Migration} */
module.exports = {
  async up(queryInterface, Sequelize) {
    await queryInterface.bulkInsert("Games", [
      {
        title: "Final Fantasy VII",
        description:
          "Dans le jeu de rôle Final Fantasy VII, le joueur incarne Cloud, ancien SOLDAT ayant rejoint le groupe terroriste Avalanche. Ce dernier essaye de déjouer les plans de la Shinra et en vient à se battre avec Sephiroth. Avec un système de combat en Active-Time et des matérias permettant de modifier les capacités des personnages, le jeu offre des mécaniques complexes et intéressantes.",
        price: 50,
        releaseDate: "1984-08-29",
        state: "bon état",
        note: 1.3,
        location: "europe",
        cover:
          "https://cdn-uploads.gameblog.fr/images/jeux/657/FinalFantasyVII_PC_Jaquette_002.jpg",
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        title: "Final Fantasy VIII",
        description:
          "Huitième épisode de la série éponyme Final Fantasy VIII est un jeu de rôle japonais. Le joueur y incarne le jeune Squall, membre dun groupe militaire délite, qui se retrouve mêlé à un conflit dépassant limagination. Il doit alors se confronter à un puissant sorcier. Les personnages de cet épisode peuvent être personnalisés avec des sorts puissants récupérés sur les ennemis. En outre, presque une heure de cinématiques en images de synthèse a été implantée.",
        price: 50,
        releaseDate: "1984-08-29",
        state: "bon état",
        note: 3.2,
        location: "europe",
        cover: "https://image.jeuxvideo.com/images/pc/f/i/fif8pc0f.jpg",
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        title: "Settlers 2",
        description:
          "The Settlers II est un jeu de gestion et de stratégie dans lequel vous bâtissez votre royaume en utilisant au mieux vos ressources. Vous pouvez jouer au mode classique où les joueurs commencent chacun avec leur château. Sinon, vous pouvez partir en mode campagne, mode qui retrace l'arrivée de colons, plus précisément des romains. Étape par étape parvenez au sommet de la civilisation.",
        price: 50,
        releaseDate: "1984-08-29",
        state: "bon état",
        note: 1.3,
        location: "europe",
        cover: "https://bigboxcollection.com/images/cover/webp/Settlers2.webp",
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        title: "Day Of The Tentacle",
        description:
          "Day of the Tentacle est un jeu d'aventure sur PC faisant suite à Maniac Mansion. On y retrouve d'ailleurs le personnage de Bernard qui, accompagné par deux amis Hoogie et Laverne, devra sauver l'humanité de l'emprise des tentacules créés par le Dr Fred. Humour, anachronismes et voyages dans le temps sont au programme du jeu aux graphismes cartoon.",
        price: 50,
        releaseDate: "1984-08-29",
        state: "bon état",
        note: 4.1,
        location: "europe",
        cover:
          "https://bigboxcollection.com/images/cover/webp/DayOfTheTentacle.webp",
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        title: "Alone in The Dark",
        description:
          "Alone in the Dark sur PC est un survival-horror qui vous propose d'évoluer dans le mystérieux manoir de Derceto, peuplé de créatures démoniaques. Vous incarnez au choix le détective Edward Carnby ou Emily Hartwood, nièce du propriétaire, pour percer les mystères de cette inquiétante demeure.",
        price: 120,
        releaseDate: "1992-04-30",
        state: "bon état",
        note: 3.3,
        location: "europe",
        cover:
          "https://image.jeuxvideo.com/images/jaquettes/00000052/jaquette-alone-in-the-dark-pc-cover-avant-g-1403787758.jpg",
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        title: "Maniac Mansion",
        description:
          "Maniac Mansion Deluxe est un jeu d'aventure sur PC dans lequel il vous incombe de tirer des griffes du docteur Edison la petite amie du héros, qui a été kidnappée par ce savant fou. Dans ce jeu teinté de beaucoup d'humour, de nombreuses énigmes doivent être résolues et vous pouvez choisir vos trois héros parmi une petite bande de personnages. Notez que Maniac Mansion Deluxe est un remake non officiel du célèbre jeu de LucasArts.",
        price: 50,
        releaseDate: "1984-08-29",
        state: "bon état",
        note: 2.3,
        location: "europe",
        cover:
          "https://cdn-products.eneba.com/resized-products/HLQvdAD7OSRY78P22EHpz7h5o8PJL2kYkmdYwoTy_QE_350x200_1x-0.jpeg",
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        title: "Hand of Fate : Legend of Kyrandia",
        description:
          "Hand of Fate est un jeu d'aventure qui constitue le deuxième volet de la trilogie des Legend of Kyrandia. Vous incarnez Zanthia, une jeune sorcière. Le monde de Kyrandia est en train de couler et c'est à vous que revient la lourde tâche de le sauver. Le jeu se présente sous la forme d'un jeu d'aventure classique, avec une succession d'écrans où le joueur peut interagir avec quelques éléments du décor.",
        price: 50,
        releaseDate: "1984-08-29",
        state: "bon état",
        note: 4.3,
        location: "europe",
        cover: "https://image.jeuxvideo.com/images/pc/l/o/lok2pc0f.jpg",
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        title: "The Blues Brothers",
        description:
          "The Blues Brothers est un jeu d'action plates-formes sur PC. Alors qu'ils sont poursuivis par la justice, vous pouvez prendre le contrôle des deux Blues Brothers : Jake ou Elwood à travers 5 niveaux (prison, rivière, grande ville...). Ramassez des bonus pour vous défaire de vos ennemis et retrouver vos disques perdus.",
        price: 120,
        releaseDate: "1991-07-24",
        state: "bon état",
        note: 3.3,
        location: "europe",
        cover:
          "https://image.jeuxvideo.com/images/jaquettes/00027786/jaquette-the-blues-brothers-pc-cover-avant-g.jpg",
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        title: "Forsaken",
        description:
          "Forsaken est un jeu d'action. Le soft vous plonge dans un univers post-apocalyptique sur la Terre. Ainsi dans la peau d'un charognard sur une moto, vous traversez des installations militaires, des centrales nucléaires et bien d'autres environnements variés. Grâce à différentes armes surpuissantes, vous pouvez écarter tous les dangers qui jalonnent votre route.",
        price: 120,
        releaseDate: "1998-04-24",
        state: "bon état",
        note: 3.3,
        location: "europe",
        cover: "https://image.jeuxvideo.com/images/pc/f/o/forspc0f.jpg",
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        title: "Revenant",
        description:
          "Revenant est un jeu de rôle sur PC. Il y a bien longtemps, votre sombre et glorieuse existence de guerrier courageux, téméraire et habile à l'arme blanche, s'est terminée sur une croix, investie par les flammes d'un bûcher qui consuma vos derniers soupirs. Bien plus tard, un éminent sorcier, Sardok, vous ramène à la vie. L'aventure commence...",
        price: 120,
        releaseDate: "1990-01-16",
        state: "bon état",
        note: 3.3,
        location: "europe",
        cover: "https://image.jeuxvideo.com/images/pc/r/e/revnpc0f.jpg",
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        title: "Loom",
        description:
          "Loom est un jeu d'aventure sur Atari ST. Vous incarnez Bobbin Threadbare, un jeune homme de 17 ans qui appartient au clan des Tisserands. Le Conseil des Anciens est attaqué et les aînés sont transformés en cygnes. Vous devez trouver les responsables et rétablir l'ordre dans la Guilde. Tout le gameplay repose sur l'utilisation de sorts musicaux pour interagir avec l'environnement.",
        price: 120,
        releaseDate: "1999-11-24",
        state: "bon état",
        note: 3.3,
        location: "europe",
        cover: "https://image.jeuxvideo.com/images/pc/l/o/loompc0f.jpg",
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        title: "Wing Commander : Prophecy",
        description:
          "Wing Commander : Prophecy est un jeu de tir spatial sur PC. Le joueur incarne Lance Casey dans sa nouvelle assignation à bord du TCS Midway. En vous promenant dans le vaisseau, vous déclenchez diverses missions et divers briefings. Vous partez donc avec un chasseur du TCS Midway pour remplir vos objectifs, dans des niveaux de tir à la première personne.",
        price: 120,
        releaseDate: "1997-11-30",
        state: "bon état",
        note: 3.3,
        location: "europe",
        cover: "https://image.jeuxvideo.com/images/pc/w/x/wxprpc0f.jpg",
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        title: "Diablo",
        description:
          "Diablo sur PC est un hack'n slash dans lequel vous incarnez un personnage à choisir parmi trois classes. Votre but est d'explorer les souterrains d'un château en exterminant les monstres qui s'y trouvent afin d'accumuler de l'expérience et des objets pour devenir de plus en plus fort. Avancez et débusquez le mal au fond de sa tanière : éliminez Diablo pour récupérer la pierre d'âme et ainsi contenir le fléau qui ronge le monde.",
        price: 120,
        releaseDate: "1996-11-30",
        state: "bon état",
        note: 3.3,
        location: "europe",
        cover: "https://bigboxcollection.com/images/cover/webp/DiabloUS.webp",
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        title: "Diablo : Hellfire",
        description:
          "Hellfire est le nom de la seule et unique extension disponible pour le hack'n slash Diablo sur PC. Celle-ci rajoute de nombreuses possibilités au jeu original, en particulier huit niveaux supplémentaires, ainsi qu'une nouvelle classe de personnages : le moine. Deux autres personnages, le barde et le barbare, sont accessibles mais ils sont à débloquer. Hellfire donne aussi la possibilité de jouer en multijoueur.",
        price: 120,
        releaseDate: "1997-06-20",
        state: "bon état",
        note: 3.3,
        location: "europe",
        cover: "https://image.jeuxvideo.com/images/pc/h/f/hfirpc0f.jpg",
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        title: "Diablo II",
        description:
          "Diablo II sur Mac est la suite du célèbre hack'n slash des studios Blizzard. Retrouvez un univers fantastique et sombre en incarnant l'une des cinq classes de personnages du jeu. Préparez-vous à voyager dans des contrées lointaines, à combattre de nouveaux ennemis, à découvrir des trésors inconnus et à dévoiler des mystères ancestraux. Tout cela dans votre quête pour arrêter une fois pour toutes le Seigneur de la Terreur...",
        price: 120,
        releaseDate: "2000-06-30",
        state: "bon état",
        note: 3.3,
        location: "europe",
        cover: "https://image.jeuxvideo.com/images/pc/d/i/dia2pc0f.jpg",
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        title: "Diablo II : Lord of Destruction",
        description:
          "Dans l'extension Lord of Destruction pour Diablo II sur Mac, vous retournez suivre le chemin de Baal, le dernier des Démons Originels dans les Hautes Terres Barbares du nord. Voyageant avec ses cohortes démoniaques, Baal a l'intention de corrompre la puissante Pierre Eternelle qui protège le plan terrestre des forces du Mal. Deux nouvelles classes de personnages (l'Assassin et le Druide) avec chacun 30 aptitudes et sorts uniques font leur apparition.",
        price: 120,
        releaseDate: "2001-06-29",
        state: "bon état",
        note: 3.3,
        location: "europe",
        cover: "https://image.jeuxvideo.com/images/pc/d/l/dlodpc0f.jpg",
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        title: "Resident Evil",
        description:
          "Resident Evil est un jeu de Survival-horror dans lequel le joueur incarne un membre de l'équipe Alpha cherchant ses compagnons disparus. Poursuivis par des créatures monstrueuses, les personnages se réfugient dans un manoir près de Racoon-City, mais le sentiment de sécurité est de courte durée...",
        price: 120,
        releaseDate: "1996-08-01",
        state: "bon état",
        note: 3.3,
        location: "europe",
        cover: "https://image.jeuxvideo.com/images/pc/r/e/reevpc0f.jpg",
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        title: "Resident Evil 2",
        description:
          "Suite du premier opus du même nom, Resident Evil 2 est un survival-horror dans lequel le joueur peut incarner Leon S. Kennedy et Claire Redfield. Ces derniers tentent de mettre à jour les plans de l'organisation Umbrella alors que la ville de Racoon City est entièrement infestée par le virus-T.",
        price: 120,
        releaseDate: "1998-08-05",
        state: "bon état",
        note: 3.3,
        location: "europe",
        cover: "https://image.jeuxvideo.com/images/pc/r/e/res2pc0f.jpg",
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        title: "Resident Evil 3 : Nemesis",
        description:
          "Se passant en même temps que l'épisode 2, Resident Evil 3 : Nemesis est un survival-horror dans lequel le joueur contrôle Jill Valentine. Cette dernière tente de s'échapper de Raccon City, ravagée par le virus-T, mais elle est poursuivie par un monstre en apparence invincible et pouvant surgir à tout moment : Nemesis.",
        price: 120,
        releaseDate: "2000-02-18",
        state: "bon état",
        note: 3.3,
        location: "europe",
        cover: "https://image.jeuxvideo.com/images/pc/r/e/res3pc0f.jpg",
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        title: "Resident Evil : Code : Veronica",
        description:
          "L'action de Resident Evil : Code : Veronica sur Dreamcast prend source deux mois après les événements de Resident Evil 2 et 3. Claire Redfield toujours à la recherche de son frère Chris, infiltre Umbrella, mais est démasquée, puis emprisonnée sur une île. Une fois libérée, elle doit faire face aux créatures, victimes une fois de plus, du virus-T.",
        price: 120,
        releaseDate: "2000-05-26",
        state: "bon état",
        note: 3.3,
        location: "europe",
        cover: "https://image.jeuxvideo.com/images/dc/r/e/recvdc0f.jpg",
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        title: "Afterlife",
        description:
          "Afterlife est un jeu de stratégie sorti sur Mac. Après votre mort vous êtes bombardé dieu tout puissant sur une autre planète où l'enfer et le paradis n'existent pas. Vous devrez préparer les habitants pour leur long voyage qui les mènera de vie à trépas.",
        price: 120,
        releaseDate: "1996-05-26",
        state: "bon état",
        note: 3.3,
        location: "europe",
        cover: "https://image.jeuxvideo.com/images/pc/a/f/aftlpc0f.jpg",
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        title: "Crusaders of Might and Magic",
        description:
          "Crusaders of Might and Magic sur PC est une déclinaison action/aventure de la licence fantasy des Might and Magic. Embarqué dans une croisade contre une armée de morts-vivants, Drake trouve enfin un moyen de venger son village détruit quelques années auparavant. Les 25 niveaux de ce soft à la troisième personne sont répartis en 5 mondes différents.",
        price: 120,
        releaseDate: "2000-05-26",
        state: "bon état",
        note: 3.3,
        location: "europe",
        cover: "https://image.jeuxvideo.com/images/pc/c/r/crmmpc0f.jpg",
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        title: "Baldur's Gate",
        description:
          " Baldur's Gate se déroule au sein d'un univers de Donjons & Dragons. Vous créez un avatar en choisissant parmi diverses classes, compétences et caractéristiques. Le joueur est alors entraîné dans une aventure où se succèdent phases de dialogue, découverte de la Côte des Épées et combats tactiques.",
        price: 120,
        releaseDate: "1999-01-05",
        state: "bon état",
        note: 3.3,
        location: "europe",
        cover: "https://image.jeuxvideo.com/images/pc/b/g/bgatpc0f.jpg",
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        title: "Baldur's Gate : La Légende de l'Ile Perdue",
        description:
          " La Légende de l'Ile Perdue est la première extension du jeu Baldur's Gate sur PC. Elle ajoute à ce dernier de nouvelles zones à explorer ainsi que de nouveaux équipements, sorts et quêtes annexes. La correction de divers bugs est aussi effectuée. Le jeu original est nécessaire pour installer et jouer à l'extension.",
        price: 120,
        releaseDate: "1999-05-28",
        state: "bon état",
        note: 3.3,
        location: "europe",
        cover: "https://image.jeuxvideo.com/images/pc/l/l/llippc0f.jpg",
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        title: "Baldur's Gate II : Throne of Bhaal",
        description:
          "Throne of Bhaal est l'extension du jeu Baldur's Gate II : Shadows of Amn et se charge d'ajouter une suite et une fin au scénario de la saga. La limite de niveau d'expérience est repoussée avec de compétences et des sortilèges inédits. De nouveaux équipements et de nouvelles quêtes font aussi leur apparition. Le jeu original est nécessaire pour installer et jouer à l'extension.",
        price: 120,
        releaseDate: "2001-06-20",
        state: "bon état",
        note: 3.3,
        location: "europe",
        cover: "https://image.jeuxvideo.com/images/pc/b/2/b2thpc0f.jpg",
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        title: "Shogo : Mobile Armor Division",
        description:
          "Shogo : Mobile Armor Division est un jeu de tir à la première personne sur Mac. Tout au long des nombreux niveaux de SHOGO (environ une quarantaine), vous opérerez en extérieur, dans des bases spatiales ou dans des dédales de souterrains. Vous serez en permanence en liaison radio avec vos supérieurs qui vous diront étape après étape comment doit se dérouler votre mission.",
        price: 120,
        releaseDate: "1998-06-20",
        state: "bon état",
        note: 3.3,
        location: "europe",
        cover: "https://image.jeuxvideo.com/images/pc/s/h/shogpc0f.jpg",
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        title: "Homeworld",
        description:
          "Homeworld est un jeu de stratégie sorti sur PC qui vous place à la tête du Vaisseau Mère. Après plus de mille ans d'histoire, la découverte des restes d'un vaisseau spatial en plein désert relance le débat sur l'origine des habitants de la très inhospitalière planète Kharak.",
        price: 120,
        releaseDate: "1999-06-20",
        state: "bon état",
        note: 3.3,
        location: "europe",
        cover:
          "https://image.jeuxvideo.com/images/jaquettes/00000009/jaquette-homeworld-pc-cover-avant-g-1374514923.jpg",
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        title: "The Legend of Kyrandia : Malcolm's Revenge",
        description:
          "Le jeu d'aventure The Legend of Kyrandia : Malcolm's Revenge sur PC est le troisième volet de la série de Kyrandia. Cette fois, vous incarnez le méchant bouffon Malcolm qui doit répondre de ses actes (la transformation en pierre de son entourage) et prouver qu'il n'a pas tué le Roi et la Reine. Explorez les souvenirs du personnages pour démêler le vrai du faux et aboutir à l'une des trois fins de l'aventure.",
        price: 120,
        releaseDate: "1994-06-20",
        state: "bon état",
        note: 3.3,
        location: "europe",
        cover: "https://image.jeuxvideo.com/images/pc/t/l/tlokpc0f.jpg",
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        title: "The Legend of Kyrandia",
        description:
          "Le bouffon Malcolm souhaite se venger du magicien Kallak et transforme ce dernier en statue de pierre avant de s'en prendre au royaume de Kyrandia. Vous êtes Brandon, le petit-fils de Kallak et vous devez rétablir la situation pour sauver le Monde. Legend of Kyrandia est un jeu d'aventure sur Amiga qui vous demandera de récupérer de nombreux objets dans les décors féeriques pour les utiliser plus tard au cours d'énigmes ou de préparations de sortilèges.",
        price: 120,
        releaseDate: "1992-04-12",
        state: "bon état",
        note: 3.3,
        location: "europe",
        cover:
          "https://image.jeuxvideo.com/images/jaquettes/00015111/jaquette-the-legend-of-kyrandia-pc-cover-avant-g-1317220593.jpg",
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        title: "Age of Empires",
        description:
          "Jeu de stratégie, Age of Empires vous invite à établir votre propre empire. Qu'allez-vous faire ? Conquérir des civilisations ennemies ? Découvrir les secrets du monde ? En tant que guide, plusieurs voies s'offrent à vous. Le soft est jouable jusqu'à 8 joueurs en réseau local ou sur internet.",
        price: 120,
        releaseDate: "1997-04-12",
        state: "bon état",
        note: 3.3,
        location: "europe",
        cover: "https://image.jeuxvideo.com/images/pc/a/o/aoempc0f.jpg",
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        title: "Age of Empires II : The Age of Kings",
        description:
          "Age of Empires II : The Age of Kings est un jeu de stratégie mettant en avant la période médiévale. Dans cet épisode rempli de grandes figures historiques, telles que Jeanne D'Arc et Saladin, ou encore Gengis Kahn et Yoshidune, le joueur doit construire son empire et le faire évoluer pour régner.",
        price: 120,
        releaseDate: "1999-09-30",
        state: "bon état",
        note: 3.3,
        location: "europe",
        cover: "https://image.jeuxvideo.com/images/pc/a/o/aoe2pc0f.jpg",
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        title: "Age of Empires II : The Conquerors Expansion",
        description:
          "The Conquerors est l'unique extension d'Age of Empires II sur PC. Au menu des nouveautés : quatre campagnes historiques (Attila, le Cid, Montezuma et les Conquérants), cinq civilisations (Aztèques, Mayas, Huns, Espagnols et Coréens) et 26 technologies dont l'herbe médicinale, la théocratie ou encore les caravanes.",
        price: 120,
        releaseDate: "2000-08-24",
        state: "bon état",
        note: 3.3,
        location: "europe",
        cover: "https://image.jeuxvideo.com/images/pc/a/o/aoecpc0f.jpg",
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        title: "Age of Empires : The Rise of Rome",
        description:
          "Age of Empires : The Rise of Rome est un jeu de stratégie sur PC. Ce soft est l'add-on officiel du jeu d'ores et déjà célèbre Age of Empires. Ainsi vous découvrirez les campagnes et la course au pouvoir en reconstituant la civilisation la plus redoutée de l'Antiquité : l'Empire romain. De plus, de nouvelles unités et civilisations sont ajoutées dans cet opus.",
        price: 120,
        releaseDate: "1998-11-24",
        state: "bon état",
        note: 3.3,
        location: "europe",
        cover: "https://image.jeuxvideo.com/images/pc/a/o/aoerpc0f.jpg",
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        title: "Age of Mythology",
        description:
          "Age of Mythology est un jeu de stratégie sorti sur PC. Incarnez une des 3 civilisations antiques possédant chacune des unités particulières. Appelez à la rescousse les dieux et usez de leurs divins pouvoirs pour réduire à néant vos adversaires.",
        price: 120,
        releaseDate: "2002-11-20",
        state: "bon état",
        note: 3.3,
        location: "europe",
        cover: "https://image.jeuxvideo.com/images-sm/pc/a/o/aomypc0f.jpg",
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        title: "Age of Mythology : Tale of the Dragon",
        description:
          "Age of Mythology : Tale of the Dragon est la nouvelle extension du très connu Age of Mythology, épisode de la franchise Age of Empire. Plus de 10 ans après sa sortie, le studio Forgotten Empires annonce le développement d'une seconde extension au jeu, après celle dédiée aux Titans.",
        price: 120,
        releaseDate: "2016-01-28",
        state: "bon état",
        note: 3.3,
        location: "europe",
        cover:
          "https://image.jeuxvideo.com/medias/144284/1442840667-5346-jaquette-avant.jpg",
        createdAt: new Date(),
        updatedAt: new Date(),
      },
    ]);
  },

  async down(queryInterface, Sequelize) {
    await queryInterface.bulkDelete("Games", null, {});
  },
};
